import './globals.css'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className='h-16 bg-yellow-300 px-4 flex'>
          <form action="/items" className='flex max-w-screen-xl m-auto flex-1 gap-4'>
            <input className='h-8 flex-1 text-gray-700 px-2' type="text" name="search" />
            <button className='h-8 bg-gray-300 px-2 py-1 text-slate-700' type='submit'>Buscar</button>
          </form>
        </header>
        <main className='max-w-screen-xl p-4'>{children}</main>
      </body>
    </html>
  )
}
