import './globals.css'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className='h-16 bg-yellow-300 px-4 '>
          <form action="/items" className='max-w-screen-xl m-auto'>
            <input type="text" name="search" />
            <button type='submit'>Buscar</button>
          </form>
        </header>
        <main className='max-w-screen-xl p-4'>{children}</main>
      </body>
    </html>
  )
}
